/**
 * The Memes Arcade catalog.
 *
 * Every game from the original wish list appears here.  `engine` is the id of
 * the shared rules module in web/games/engines/*.js - when that module exists
 * the entry is playable everywhere (website, desktop client, Discord activity
 * bridge); when it is null the entry shows in the catalog as planned work.
 *
 * Variants (Go Fish "anime/drawn/humans", Sudoku "race", Kahoot-style modes,
 * Gartic Phone presets...) are options on one engine rather than copies.
 *
 * Pure data: imported by the browser *and* by the Node server.
 */

const P = (min, max = min) => ({ min, max });

export const CATEGORIES = [
  { id: 'board', name: 'Board & Classics', icon: '♟️' },
  { id: 'cards', name: 'Cards & Table', icon: '🃏' },
  { id: 'drawing', name: 'Drawing & Guessing', icon: '🎨' },
  { id: 'party', name: 'Party & Writing', icon: '🎉' },
  { id: 'quiz', name: 'Quiz Show', icon: '❓' },
  { id: 'social', name: 'Social Deduction', icon: '🕵️' },
  { id: 'arcade', name: 'Arcade', icon: '🕹️' },
  { id: 'puzzle', name: 'Puzzles', icon: '🧩' },
];

export const GAMES = [
  /* ------------------------------ board ------------------------------ */
  {
    id: 'tic-tac-toe',
    name: 'Tic-Tac-Toe',
    icon: '❌',
    category: 'board',
    players: P(2),
    modes: ['solo', 'local', 'online'],
    blurb: 'The classic three-in-a-row. Rounds are instant, bots are ruthless.',
    tags: ['classic', 'quick', '1v1'],
    minutes: 2,
    status: 'playable',
    engine: 'tic-tac-toe',
  },
  {
    id: 'ultimate-ttt',
    name: 'Ultimate Tic-Tac-Toe',
    icon: '🔲',
    category: 'board',
    players: P(2),
    modes: ['solo', 'local', 'online'],
    blurb: 'Nine boards in one. Your move decides where your rival must play next.',
    tags: ['classic', 'strategy', '1v1'],
    minutes: 12,
    status: 'playable',
    engine: 'ultimate-ttt',
  },
  {
    id: 'connect-four',
    name: 'Connect Four',
    icon: '🔴',
    category: 'board',
    players: P(2),
    modes: ['solo', 'local', 'online'],
    blurb: 'Drop discs, stack four. Bots look several moves ahead.',
    tags: ['classic', '1v1', 'quick'],
    minutes: 5,
    status: 'playable',
    engine: 'connect-four',
  },
  {
    id: 'checkers',
    name: 'Checkers',
    icon: '⚫',
    category: 'board',
    players: P(2),
    modes: ['solo', 'local', 'online'],
    blurb: 'Draughts with forced captures, multi-jumps and king promotion.',
    tags: ['classic', '1v1'],
    minutes: 15,
    status: 'playable',
    engine: 'checkers',
  },
  {
    id: 'chess',
    name: 'Chess',
    icon: '♞',
    category: 'board',
    players: P(2),
    modes: ['solo', 'local', 'online'],
    blurb: 'Full legal move generation: castling, en passant, promotion, check and mate.',
    tags: ['classic', 'strategy', '1v1'],
    minutes: 25,
    status: 'playable',
    engine: 'chess',
  },
  {
    id: 'battleship',
    name: 'Battleship',
    icon: '🚢',
    category: 'board',
    players: P(2),
    modes: ['solo', 'local', 'online'],
    blurb: 'Hide your fleet, then hunt theirs. Your board stays secret.',
    tags: ['1v1', 'naval'],
    minutes: 15,
    status: 'playable',
    engine: 'battleship',
  },

  /* ------------------------------ cards ------------------------------ */
  {
    id: 'uno',
    name: 'UNO',
    icon: '🎴',
    category: 'cards',
    players: P(2, 10),
    modes: ['solo', 'local', 'online'],
    blurb: 'Wilds, +2s, +4s, reverses and that one friend who never says UNO.',
    tags: ['cards', 'party'],
    minutes: 15,
    status: 'playable',
    engine: 'uno',
  },
  {
    id: 'go-fish',
    name: 'Go Fish',
    icon: '🐟',
    category: 'cards',
    players: P(2, 8),
    modes: ['solo', 'local', 'online'],
    blurb: 'Ask for cards, make books. Deck themes: classic, anime cast, our drawn art, or your party avatars.',
    tags: ['cards', 'chill'],
    minutes: 10,
    status: 'playable',
    engine: 'go-fish',
    variants: [
      { id: 'anime', name: 'Anime cast', desc: 'Character-card deck drawn from anime favourites.' },
      { id: 'drawn', name: 'Drawn by us', desc: 'Cards use in-house sketch art (drop more art in web/assets/cards).' },
      { id: 'humans', name: 'Humans', desc: 'Each player is a card - collect your friends.' },
    ],
  },
  {
    id: 'blackjack',
    name: '21 / Blackjack',
    icon: '🂡',
    category: 'cards',
    players: P(1, 7),
    modes: ['solo', 'local', 'online'],
    blurb: 'Hit, stand, double or split. Dealer stands on 17. Coins are fake, pride is real.',
    tags: ['cards', 'quick'],
    minutes: 5,
    status: 'playable',
    engine: 'blackjack',
  },
  {
    id: 'monopoly',
    name: 'Monopoly',
    icon: '🎩',
    category: 'cards',
    players: P(2, 6),
    modes: ['local', 'online'],
    blurb: 'A trimmed, fast-playing board: buy, rent, trade-free, go to jail, bankrupt your friends.',
    tags: ['dice', 'long', 'beta'],
    minutes: 45,
    status: 'beta',
    engine: 'monopoly',
  },

  /* ----------------------------- drawing ----------------------------- */
  {
    id: 'gartic-phone',
    name: 'Gartic Phone',
    icon: '📞',
    category: 'drawing',
    players: P(3, 16),
    modes: ['local', 'online'],
    blurb: 'Write, draw, guess, repeat - then watch the telephone chain fall apart hilariously.',
    tags: ['drawing', 'party', 'flagship'],
    minutes: 20,
    status: 'playable',
    engine: 'gartic-phone',
    variants: [
      { id: 'classic', name: 'Classic', desc: 'Prompt -> drawing -> guess -> drawing chain.' },
      { id: 'exquisite-corpse', name: 'Exquisite Corpse', desc: 'Everyone draws ONE body part: head, left arm, right arm, left leg, right leg - stacked blind.' },
      { id: 'blind', name: 'Blind Draw', desc: 'You only see the last 300ms of the previous drawing.' },
      { id: 'speed', name: 'Speedrun', desc: 'Fifteen second turns, no takebacks.' },
      { id: 'story-corpse', name: 'Story Corpse', desc: 'Alternate sentence / drawing turns to build an illustrated story.' },
    ],
  },
  {
    id: 'charades-draw',
    name: 'Charades (Draw)',
    icon: '✏️',
    category: 'drawing',
    players: P(2, 10),
    modes: ['local', 'online'],
    blurb: 'One player draws a secret word while everyone else races to guess it in chat.',
    tags: ['drawing', 'party'],
    minutes: 15,
    status: 'playable',
    engine: 'charades-draw',
  },
  {
    id: 'bad-drawing',
    name: 'Bad Drawing Challenge',
    icon: '😵',
    category: 'drawing',
    players: P(3, 12),
    modes: ['local', 'online'],
    blurb: 'Draw with a wobbly brush, wrong colours and no undo. Worst drawing wins votes.',
    tags: ['drawing', 'comedy'],
    minutes: 12,
    status: 'playable',
    engine: 'bad-drawing',
  },
  {
    id: 'meme-maker',
    name: 'Meme Maker Battle',
    icon: '🖼️',
    category: 'drawing',
    players: P(2, 12),
    modes: ['solo', 'local', 'online'],
    blurb: 'Everyone gets the same template and 90 seconds. Caption text on canvas, then vote for the best.',
    tags: ['memes', 'party'],
    minutes: 10,
    status: 'playable',
    engine: 'meme-maker',
  },
  {
    id: 'spot-difference',
    name: 'Spot the Difference',
    icon: '🔍',
    category: 'puzzle',
    players: P(1, 8),
    modes: ['solo', 'local', 'online'],
    blurb: 'Scenes are generated on the fly with N sneaky differences. Click them before your rivals.',
    tags: ['puzzle', 'race'],
    minutes: 8,
    status: 'playable',
    engine: 'spot-difference',
  },

  /* ------------------------------ party ------------------------------ */
  {
    id: 'quiplash',
    name: 'Quiplash',
    icon: '💬',
    category: 'party',
    players: P(3, 12),
    modes: ['local', 'online'],
    blurb: 'Two prompts, one joke each, then everyone votes. Grab your "Quiplash!" moment.',
    tags: ['party', 'writing', 'flagship'],
    minutes: 15,
    status: 'playable',
    engine: 'quiplash',
  },
  {
    id: 'caption-battle',
    name: 'Caption Battle',
    icon: '📸',
    category: 'party',
    players: P(3, 14),
    modes: ['local', 'online'],
    blurb: 'Same image for everyone, anonymous captions, then vote for the funniest.',
    tags: ['party', 'writing', 'memes'],
    minutes: 12,
    status: 'playable',
    engine: 'caption-battle',
  },
  {
    id: 'funny-answers',
    name: 'Answer!',
    icon: '🤪',
    category: 'party',
    players: P(2, 14),
    modes: ['local', 'online'],
    blurb: 'We ask something daft. You answer in the funniest way you can. Everyone votes.',
    tags: ['party', 'writing'],
    minutes: 12,
    status: 'playable',
    engine: 'funny-answers',
  },
  {
    id: 'hot-take',
    name: 'Hot Take',
    icon: '🔥',
    category: 'party',
    players: P(2, 14),
    modes: ['local', 'online'],
    blurb: 'Take a side on a ridiculous opinion, then argue it with a one-liner. Crowd picks the winner.',
    tags: ['party', 'debate'],
    minutes: 10,
    status: 'playable',
    engine: 'hot-take',
  },
  {
    id: 'telephone-story',
    name: 'Telephone Story',
    icon: '☎️',
    category: 'party',
    players: P(3, 14),
    modes: ['local', 'online'],
    blurb: 'Each player writes one sentence, then passes it along. Hilarity by Chinese whispers.',
    tags: ['party', 'writing'],
    minutes: 12,
    status: 'playable',
    engine: 'telephone-story',
  },
  {
    id: 'story-builder',
    name: 'Story Builder',
    icon: '📖',
    category: 'party',
    players: P(2, 14),
    modes: ['local', 'online'],
    blurb: 'Everyone adds one sentence to a shared story until it collapses under its own plot.',
    tags: ['party', 'writing'],
    minutes: 12,
    status: 'playable',
    engine: 'story-builder',
  },
  {
    id: 'one-word-story',
    name: 'One Word Story',
    icon: '🔤',
    category: 'party',
    players: P(2, 16),
    modes: ['local', 'online'],
    blurb: 'Each player contributes exactly one word. Chaotic literature ensues.',
    tags: ['party', 'writing', 'quick'],
    minutes: 8,
    status: 'playable',
    engine: 'one-word-story',
  },
  {
    id: 'plot-twist',
    name: 'Plot Twist',
    icon: '🌀',
    category: 'party',
    players: P(2, 12),
    modes: ['local', 'online'],
    blurb: 'Build a story, but every round forces a random plot twist you must write into it.',
    tags: ['party', 'writing'],
    minutes: 15,
    status: 'playable',
    engine: 'plot-twist',
  },
  {
    id: 'fake-definition',
    name: 'Fake Definition',
    icon: '📚',
    category: 'party',
    players: P(3, 12),
    modes: ['local', 'online'],
    blurb: 'You get a bizarre real word. Invent a definition convincing enough to fool everyone.',
    tags: ['party', 'writing', 'bluff'],
    minutes: 12,
    status: 'playable',
    engine: 'fake-definition',
  },
  {
    id: 'emoji-story',
    name: 'Emoji Story',
    icon: '😂',
    category: 'party',
    players: P(2, 12),
    modes: ['local', 'online'],
    blurb: 'Tell a whole story using only emojis. Others guess what on earth happened.',
    tags: ['party', 'quick'],
    minutes: 8,
    status: 'playable',
    engine: 'emoji-story',
  },
  {
    id: 'guess-the-story',
    name: 'Guess the Story',
    icon: '🕵️‍♀️',
    category: 'party',
    players: P(3, 12),
    modes: ['local', 'online'],
    blurb: 'A strange story is revealed one piece at a time. Guess what actually happened.',
    tags: ['party', 'deduction'],
    minutes: 10,
    status: 'playable',
    engine: 'guess-the-story',
  },

  /* ------------------------------- quiz ------------------------------ */
  {
    id: 'trivia',
    name: 'Trivia',
    icon: '🧠',
    category: 'quiz',
    players: P(1, 16),
    modes: ['solo', 'local', 'online'],
    blurb: 'Hundreds of questions across games, anime, science and pure nonsense. Speed matters.',
    tags: ['quiz', 'party'],
    minutes: 12,
    status: 'playable',
    engine: 'trivia',
  },
  {
    id: 'jeopardy',
    name: 'Jeopardy',
    icon: '📋',
    category: 'quiz',
    players: P(1, 8),
    modes: ['solo', 'local', 'online'],
    blurb: 'Pick a category and a value, answer in the form of a question, steal on the rebound.',
    tags: ['quiz', 'long'],
    minutes: 25,
    status: 'playable',
    engine: 'jeopardy',
  },
  {
    id: 'quiz-rush',
    name: 'Quiz Rush (Blooket-style)',
    icon: '💥',
    category: 'quiz',
    players: P(1, 16),
    modes: ['solo', 'local', 'online'],
    blurb: 'Kahoot/Blooket-flavoured modes: Classic podium, Coin Rush, Hack Attack, and Battle Royale.',
    tags: ['quiz', 'party'],
    minutes: 10,
    status: 'playable',
    engine: 'quiz-rush',
    variants: [
      { id: 'classic', name: 'Classic', desc: 'Answer fast, score points, climb the podium.' },
      { id: 'coin-rush', name: 'Coin Rush', desc: 'Steal a share of coins from whoever is leading.' },
      { id: 'hack-attack', name: 'Hack Attack', desc: 'Freeze, swap or double an opponent\'s score.' },
      { id: 'royale', name: 'Royale', desc: 'Miss three and you are eliminated. Last one standing wins.' },
    ],
  },
  {
    id: 'guess-character',
    name: 'Guess the Character',
    icon: '🎭',
    category: 'quiz',
    players: P(2, 12),
    modes: ['solo', 'local', 'online'],
    blurb: 'Clues revealed one at a time - the earlier you answer, the more you score.',
    tags: ['quiz', 'anime'],
    minutes: 10,
    status: 'playable',
    engine: 'guess-character',
  },
  {
    id: 'zoomed-image',
    name: 'Guess the Zoomed Image',
    icon: '🔬',
    category: 'puzzle',
    players: P(2, 12),
    modes: ['solo', 'local', 'online'],
    blurb: 'A scene, drawn procedurally and zoomed way in. Zoom out every few seconds - guess before it is obvious.',
    tags: ['quiz', 'visual'],
    minutes: 8,
    status: 'playable',
    engine: 'zoomed-image',
  },
  {
    id: 'guess-the-prompt',
    name: 'Prompt Guessing',
    icon: '🤖',
    category: 'puzzle',
    players: P(2, 12),
    modes: ['solo', 'local', 'online'],
    blurb: 'Abstract art generated from a hidden prompt - guess the words that made it. (Offline generator: no API key needed.)',
    tags: ['quiz', 'visual', 'ai-flavoured'],
    minutes: 8,
    status: 'playable',
    engine: 'guess-the-prompt',
  },

  /* ------------------------------ social ----------------------------- */
  {
    id: 'mafia',
    name: 'Mafia',
    icon: '🕶️',
    category: 'social',
    players: P(5, 14),
    modes: ['local', 'online'],
    blurb: 'Night kills, day accusations, doctor saves and a detective with a hunch. Full role deck.',
    tags: ['deduction', 'party', 'flagship'],
    minutes: 25,
    status: 'playable',
    engine: 'mafia',
  },
  {
    id: 'gecko',
    name: 'Gecko (Imposter)',
    icon: '🦎',
    category: 'social',
    players: P(4, 12),
    modes: ['local', 'online'],
    blurb: 'Among Us energy: everyone shares a secret word except the Gecko, who must bluff their way through.',
    tags: ['deduction', 'party'],
    minutes: 15,
    status: 'playable',
    engine: 'gecko',
  },
  {
    id: 'codenames',
    name: 'Codenames',
    icon: '🗂️',
    category: 'social',
    players: P(4, 12),
    modes: ['local', 'online'],
    blurb: 'Two spymasters, 25 words, one assassin. Give one-word clues that dodge your opponents\' agents.',
    tags: ['deduction', 'team', 'flagship', 'discord'],
    minutes: 20,
    status: 'playable',
    engine: 'codenames',
    discordActivity: true,
  },
  {
    id: 'mafia-social',
    name: 'Basic Chat',
    icon: '💬',
    category: 'social',
    players: P(1, 999),
    modes: ['online'],
    blurb: 'Just hang out. Global chat, party rooms, DMs and voice-free lobbies - no game required.',
    tags: ['feature', 'chat'],
    minutes: 1,
    status: 'playable',
    engine: null,
    feature: true,
  },

  /* ----------------------------- arcade ------------------------------ */
  {
    id: 'memes-smash',
    name: 'MEME (Smash-style)',
    icon: '🥊',
    category: 'arcade',
    players: P(2, 4),
    modes: ['solo', 'local', 'online'],
    blurb: 'Platform fighter with anime and manga fighters plus custom characters - including your own sketches.',
    tags: ['fighter', 'flagship', 'custom-art'],
    minutes: 6,
    status: 'playable',
    engine: 'memes-smash',
    rosters: ['One Piece-inspired', 'Tensura-inspired', 'Death Note-inspired', 'Manga misc', 'Custom sketches'],
  },
  {
    id: 'rocket-bot-royale',
    name: 'Rocket Bot Royale',
    icon: '🚀',
    category: 'arcade',
    players: P(2, 8),
    modes: ['solo', 'local', 'online'],
    blurb: 'Low-spec rocket arena: thrust, blast, last bot flying wins. Runs on potatoes and in Discord.',
    tags: ['shooter', 'discord', 'low-spec'],
    minutes: 6,
    status: 'playable',
    engine: 'rocket-bot-royale',
    discordActivity: true,
  },
  {
    id: 'pong',
    name: 'Ping Pong',
    icon: '🏓',
    category: 'arcade',
    players: P(2, 4),
    modes: ['solo', 'local', 'online'],
    blurb: 'Pong with spin, power-ups and a two-versus-two mode.',
    tags: ['arcade', 'quick'],
    minutes: 5,
    status: 'playable',
    engine: 'pong',
  },
  {
    id: 'invade',
    name: 'Invade',
    icon: '👾',
    category: 'arcade',
    players: P(1, 4),
    modes: ['solo', 'local', 'online'],
    blurb: 'Space Invaders-style waves with escalating formations and boss ships.',
    tags: ['arcade', 'retro'],
    minutes: 8,
    status: 'playable',
    engine: 'invade',
  },
  {
    id: 'mini-golf',
    name: 'Mini Golf',
    icon: '⛳',
    category: 'arcade',
    players: P(1, 8),
    modes: ['solo', 'local', 'online'],
    blurb: 'Nine handcrafted holes, windmills included. Fewest strokes takes the trophy.',
    tags: ['sports', 'turn-based'],
    minutes: 15,
    status: 'playable',
    engine: 'mini-golf',
  },
  {
    id: 'sudoku',
    name: 'Sudoku',
    icon: '🔢',
    category: 'puzzle',
    players: P(1, 8),
    modes: ['solo', 'local', 'online'],
    blurb: 'Real generator with difficulty tiers, hints and notes. Race mode scores whoever solves it first.',
    tags: ['puzzle', 'solo', 'race'],
    minutes: 15,
    status: 'playable',
    engine: 'sudoku',
    variants: [
      { id: 'solo', name: 'Solo puzzle', desc: 'Relax and solve at your own pace.' },
      { id: 'race', name: 'Race', desc: 'Everyone gets the same grid - first clean solve wins.' },
    ],
  },
  {
    id: 'hangman',
    name: 'Hangman',
    icon: '🪢',
    category: 'board',
    players: P(1, 8),
    modes: ['solo', 'local', 'online'],
    blurb: 'Classic letter guessing with themed word packs and mercy hints.',
    tags: ['word', 'quick'],
    minutes: 8,
    status: 'playable',
    engine: 'hangman',
  },
];

/** Look up a single catalog entry. */
export function gameById(id) {
  return GAMES.find((g) => g.id === id) || null;
}

/**
 * Merge live engine metadata into the catalog so the client can show what is
 * actually playable right now (and the rules/options each engine exposes).
 */
export function catalogWithEngines(engineList = []) {
  const byId = new Map(engineList.map((e) => [e.id, e]));
  return GAMES.map((game) => {
    const engine = byId.get(game.engine || game.id);
    const playable = !!engine;
    return {
      ...game,
      playable,
      status: playable ? game.status : 'planned',
      engineMeta: engine || null,
      players: engine?.players || game.players,
      modes: engine?.modes || game.modes,
      variants: game.variants || engine?.variants || [],
    };
  });
}

export function playableGames(engineList = []) {
  return catalogWithEngines(engineList).filter((g) => g.playable);
}

/** Grouped view for the catalog UI. */
export function catalogByCategory(engineList = []) {
  const catalog = catalogWithEngines(engineList);
  return CATEGORIES.map((cat) => ({
    ...cat,
    games: catalog.filter((g) => g.category === cat.id),
  })).filter((c) => c.games.length);
}

export default { GAMES, CATEGORIES, gameById, catalogWithEngines, catalogByCategory, playableGames };
